_target_: boltzgen.task.filter.filter.Filter

budget:  30
top_budget:  10
use_affinity:  false  # This changes the filtering metrics to metrics more amenable to small molecule binder design
filter_cysteine:  false  # [different from peptide-protein] This filters out all designs that have designed cysteins in them (prespecified cysteins in the design are not counted)
from_inverse_folded:  false  # This makes it so that we use the backbone refolding rmsd instead of the all-atom RMSD
filter_bindingsite:  false  # This filters out everything that does not have a residue within 4A of a binding site residue
modality: "peptide"  # peptide or antibody
peptide_type: "linear"  # linear or cyclic
alpha:  0.001  # 0 quality-only 1 diversity-only
random_state:  0
metrics_override:  null  # overrides metrics None values delete keys
num_liability_plots:  0
plot_seq_logos:  false  # make sequence logo diagrams of designed sequence

# Complex RMSD filtering (based on diffusion samples)
filter_complex_rmsd:  false  # Filter based on number of diffusion samples passing complex RMSD threshold
min_complex_rmsd_samples:  1  # Minimum number of diffusion samples that must pass the complex RMSD threshold

